create or replace PROCEDURE ADD_ITEM_PRO
(
  ITEMID IN NUMBER 
, ITEMNAME IN VARCHAR2 
, ITEMCATEGORY IN VARCHAR2 
, STARTPRICE IN NUMBER 
, DESCRIPTION IN VARCHAR2 
, SELLERID IN NUMBER 
, AUCTIONSTARTTIME IN TIMESTAMP 
, AUCTIONENDTIME IN TIMESTAMP 
) AS 
BEGIN
  INSERT INTO team2.HARAMBASE_ITEM VALUES (ITEMID,ITEMNAME,ITEMCATEGORY,STARTPRICE,DESCRIPTION,SELLERID,AUCTIONSTARTTIME,AUCTIONENDTIME);
END ADD_ITEM_PRO;