create or replace PROCEDURE ADD_BID_PRO
(
  USERID IN NUMBER 
, TID IN NUMBER 
, MAXBIDLIMIT IN NUMBER 
, SUCC OUT INTEGER
) AS 
  STATUS INT := 0;
  STARTPRICE NUMBER := 0;
  CURRBID NUMBER := 0;
  WINNERID NUMBER := 0;
  CT INT := 0;
BEGIN
  SELECT get_status_func(TID) INTO STATUS FROM DUAL;
  SELECT HARAMBASE_GETPRICE_FUNC(TID) INTO CURRBID FROM DUAL;
  SELECT ITEM.STARTPRICE INTO STARTPRICE FROM HARAMBASE_ITEM ITEM WHERE ITEM.ITEMID = TID;
  SELECT GETWINNER_FUNC(TID) INTO WINNERID FROM DUAL;
  
  IF STATUS = 0 AND  STARTPRICE < MAXBIDLIMIT AND USERID <> WINNERID THEN
    SELECT COUNT(*) INTO CT FROM HARAMBASE_BID BID WHERE BID.USERID = USERID;
    IF CT = 1 THEN
      DELETE FROM team2.HARAMBASE_BID BID WHERE BID.USERID = USERID;
    END IF;
    INSERT INTO team2.HARAMBASE_BID VALUES (USERID, TID, CURRENT_TIMESTAMP, MAXBIDLIMIT);
    SUCC := 1; --SUCCESS
  ELSIF STATUS = 1  THEN SUCC := 2; --ITEM HAS BEEN SOLD
  ELSIF STATUS = -1 THEN SUCC := -1; --THE AUCTION HAS NOT STARTED YET
  ELSIF STATUS = 0 AND STARTPRICE >= MAXBIDLIMIT THEN SUCC := 3; --MAXLIMIT REJECTED
  ELSIF STATUS = 0 AND STARTPRICE < MAXBIDLIMIT AND USERID = WINNERID THEN SUCC := 4; --WINNER REJECTED
  END IF;
  

END ADD_BID_PRO;