--DECLARE 
-- CURMAX INTEGER;
--BEGIN
-- CURMAX := 1;
-- SELECT MAX(ITEMID) INTO CURMAX FROM HARAMBASE_ITEM;
-- IF CURMAX > 100 THEN
--    EXECUTE IMMEDIATE 'DROP SEQUENCE ITEMSEQ';
-- END IF;
-- CURMAX := CURMAX + 1;
-- EXECUTE IMMEDIATE 'CREATE SEQUENCE ITEMSEQ MINVALUE 100 MAXVALUE 1000 INCREMENT BY 1 START WITH '||CURMAX||' NOCACHE  ORDER  NOCYCLE  NOPARTITION' ;
--END;


Create or Replace Trigger GenerateItemID
BEFORE INSERT ON Harambase_ITEM
FOR EACH ROW
BEGIN
	SELECT ITEMSEQ.NEXTVAL into :new.ItemID FROM dual;
END;
