create or replace FUNCTION MEMBER_LOG_IN_FUNC 
(
  USERNAME IN VARCHAR2 
, USERPASSWORD IN VARCHAR2 
) RETURN INTEGER AS ISLOG INT := 0; --CHECK FOR USERNAME AND PASSWORD. T/F = 1/0
BEGIN
  SELECT COUNT(*) INTO ISLOG FROM HARAMBASE_MEMBER M WHERE M.UNAME = USERNAME AND M.PASSWORD = USERPASSWORD;
  RETURN ISLOG; --RETURN 1 IF COUNT IS 1.
  
END MEMBER_LOG_IN_FUNC;