create or replace PROCEDURE SEARCH_ITEM_PRO
(
  TID IN NUMBER 
, KEYWORD IN VARCHAR2 
, TCATEGORY IN VARCHAR2 
, TAUCTIONSTARTTIME IN TIMESTAMP 
, TAUCTIONENDTIME IN TIMESTAMP
, CURBIDMIN IN NUMBER
, CURBIDMAX IN NUMBER
, RESULTSET OUT SYS_REFCURSOR
) AS 
BEGIN
  
  IF TID IS NOT NULL THEN
    OPEN RESULTSET FOR 
          SELECT HI.ITEMID, HI.ITEMNAME, HI.ITEMCATEGORY, HI.AUCTIONSTARTTIME, HI.AUCTIONENDTIME, HARAMBASE_GETPRICE_FUNC(HI.ITEMID) AS CURRENTBID, GET_STATUS_FUNC(HI.ITEMID) AS STATUS
          FROM HARAMBASE_ITEM HI
          WHERE HI.ITEMID = TID;
  ELSIF KEYWORD IS NOT NULL 
        AND TCATEGORY IS NOT NULL
        AND CURBIDMIN IS NOT NULL
        AND CURBIDMAX IS NOT NULL
        AND TAUCTIONSTARTTIME IS NOT NULL
        AND TAUCTIONENDTIME IS NOT NULL THEN
    OPEN RESULTSET FOR 
          SELECT HI.ITEMID, HI.ITEMNAME, HI.ITEMCATEGORY, HI.AUCTIONSTARTTIME, HI.AUCTIONENDTIME, HARAMBASE_GETPRICE_FUNC(HI.ITEMID) AS CURRENTBID, GET_STATUS_FUNC(HI.ITEMID) AS STATUS 
          FROM HARAMBASE_ITEM HI 
          WHERE (UPPER(HI.ITEMNAME) LIKE '%'||UPPER(KEYWORD)||'%' OR SOUNDEX(KEYWORD) = SOUNDEX(HI.ITEMNAME))
          AND TCATEGORY = HI.ITEMCATEGORY AND HARAMBASE_GETPRICE_FUNC(HI.ITEMID) <= CURBIDMAX AND CURBIDMIN <= HARAMBASE_GETPRICE_FUNC(HI.ITEMID) AND 
                TAUCTIONSTARTTIME <=  HI.AUCTIONSTARTTIME AND TAUCTIONENDTIME >= HI.AUCTIONENDTIME;

  ELSIF KEYWORD IS NOT NULL 
        AND TCATEGORY IS NULL
        AND CURBIDMIN IS NOT NULL
        AND CURBIDMAX IS NOT NULL
        AND TAUCTIONSTARTTIME IS NOT NULL
        AND TAUCTIONENDTIME IS NOT NULL THEN
      OPEN RESULTSET FOR 
          SELECT HI.ITEMID, HI.ITEMNAME, HI.ITEMCATEGORY, HI.AUCTIONSTARTTIME, HI.AUCTIONENDTIME, HARAMBASE_GETPRICE_FUNC(HI.ITEMID) AS CURRENTBID, GET_STATUS_FUNC(HI.ITEMID) AS STATUS 
          FROM HARAMBASE_ITEM HI 
          WHERE (UPPER(HI.ITEMNAME) LIKE '%'||UPPER(KEYWORD)||'%' OR SOUNDEX(KEYWORD) = SOUNDEX(HI.ITEMNAME))
                AND HARAMBASE_GETPRICE_FUNC(HI.ITEMID) <= CURBIDMAX 
                AND CURBIDMIN <= HARAMBASE_GETPRICE_FUNC(HI.ITEMID) 
                AND TAUCTIONSTARTTIME <=  HI.AUCTIONSTARTTIME 
                AND TAUCTIONENDTIME >= HI.AUCTIONENDTIME;
  
  ELSIF KEYWORD IS NOT NULL 
      AND TCATEGORY IS NOT NULL
      AND CURBIDMIN IS NULL
      AND CURBIDMAX IS NULL
      AND TAUCTIONSTARTTIME IS NOT NULL
      AND TAUCTIONENDTIME IS NOT NULL THEN
    OPEN RESULTSET FOR 
        SELECT HI.ITEMID, HI.ITEMNAME, HI.ITEMCATEGORY, HI.AUCTIONSTARTTIME, HI.AUCTIONENDTIME, HARAMBASE_GETPRICE_FUNC(HI.ITEMID) AS CURRENTBID, GET_STATUS_FUNC(HI.ITEMID) AS STATUS 
        FROM HARAMBASE_ITEM HI 
        WHERE (UPPER(HI.ITEMNAME) LIKE '%'||UPPER(KEYWORD)||'%' OR SOUNDEX(KEYWORD) = SOUNDEX(HI.ITEMNAME)) 
              AND TCATEGORY = HI.ITEMCATEGORY 
              AND TAUCTIONSTARTTIME <=  HI.AUCTIONSTARTTIME 
              AND TAUCTIONENDTIME >= HI.AUCTIONENDTIME;
        
  ELSIF KEYWORD IS NOT NULL 
        AND TCATEGORY IS NOT NULL
        AND CURBIDMIN IS NOT NULL
        AND CURBIDMAX IS NOT NULL
        AND TAUCTIONSTARTTIME IS NULL
        AND TAUCTIONENDTIME IS NULL THEN
    OPEN RESULTSET FOR 
          SELECT HI.ITEMID, HI.ITEMNAME, HI.ITEMCATEGORY, HI.AUCTIONSTARTTIME, HI.AUCTIONENDTIME, HARAMBASE_GETPRICE_FUNC(HI.ITEMID) AS CURRENTBID, GET_STATUS_FUNC(HI.ITEMID) AS STATUS 
          FROM HARAMBASE_ITEM HI 
          WHERE (UPPER(HI.ITEMNAME) LIKE '%'||UPPER(KEYWORD)||'%' OR SOUNDEX(KEYWORD) = SOUNDEX(HI.ITEMNAME)) 
                AND TCATEGORY = HI.ITEMCATEGORY 
                AND HARAMBASE_GETPRICE_FUNC(HI.ITEMID) <= CURBIDMAX 
                AND CURBIDMIN <= HARAMBASE_GETPRICE_FUNC(HI.ITEMID);
 
  ELSIF KEYWORD IS NOT NULL 
        AND TCATEGORY IS NULL
        AND CURBIDMIN IS NOT NULL
        AND CURBIDMAX IS NOT NULL
        AND TAUCTIONSTARTTIME IS NULL
        AND TAUCTIONENDTIME IS NULL THEN
    OPEN RESULTSET FOR 
          SELECT HI.ITEMID, HI.ITEMNAME, HI.ITEMCATEGORY, HI.AUCTIONSTARTTIME, HI.AUCTIONENDTIME, HARAMBASE_GETPRICE_FUNC(HI.ITEMID) AS CURRENTBID, GET_STATUS_FUNC(HI.ITEMID) AS STATUS 
          FROM HARAMBASE_ITEM HI 
          WHERE (UPPER(HI.ITEMNAME) LIKE '%'||UPPER(KEYWORD)||'%' OR SOUNDEX(KEYWORD) = SOUNDEX(HI.ITEMNAME)) 
                AND HARAMBASE_GETPRICE_FUNC(HI.ITEMID) <= CURBIDMAX 
                AND CURBIDMIN <= HARAMBASE_GETPRICE_FUNC(HI.ITEMID);

  ELSIF KEYWORD IS NOT NULL 
      AND TCATEGORY IS NULL
      AND CURBIDMIN IS NULL
      AND CURBIDMAX IS NULL
      AND TAUCTIONSTARTTIME IS NOT NULL
      AND TAUCTIONENDTIME IS NOT NULL THEN
      
    OPEN RESULTSET FOR 
        SELECT HI.ITEMID, HI.ITEMNAME, HI.ITEMCATEGORY, HI.AUCTIONSTARTTIME, HI.AUCTIONENDTIME, HARAMBASE_GETPRICE_FUNC(HI.ITEMID) AS CURRENTBID, GET_STATUS_FUNC(HI.ITEMID) AS STATUS 
        FROM HARAMBASE_ITEM HI 
        WHERE (UPPER(HI.ITEMNAME) LIKE '%'||UPPER(KEYWORD)||'%' OR SOUNDEX(KEYWORD) = SOUNDEX(HI.ITEMNAME)) 
              AND TAUCTIONSTARTTIME <=  HI.AUCTIONSTARTTIME 
              AND TAUCTIONENDTIME >= HI.AUCTIONENDTIME;
   
  ELSIF KEYWORD IS NOT NULL 
      AND TCATEGORY IS NOT NULL
      AND CURBIDMIN IS NULL
      AND CURBIDMAX IS NULL
      AND TAUCTIONSTARTTIME IS  NULL
      AND TAUCTIONENDTIME IS NULL THEN
    OPEN RESULTSET FOR 
        SELECT HI.ITEMID, HI.ITEMNAME, HI.ITEMCATEGORY, HI.AUCTIONSTARTTIME, HI.AUCTIONENDTIME, HARAMBASE_GETPRICE_FUNC(HI.ITEMID) AS CURRENTBID, GET_STATUS_FUNC(HI.ITEMID) AS STATUS 
        FROM HARAMBASE_ITEM HI 
        WHERE (UPPER(HI.ITEMNAME) LIKE '%'||UPPER(KEYWORD)||'%' OR SOUNDEX(KEYWORD) = SOUNDEX(HI.ITEMNAME)) AND TCATEGORY = HI.ITEMCATEGORY;
                
  ELSIF KEYWORD IS NOT NULL 
      AND TCATEGORY IS NULL
      AND CURBIDMIN IS NULL
      AND CURBIDMAX IS NULL
      AND TAUCTIONSTARTTIME IS NULL
      AND TAUCTIONENDTIME IS NULL THEN
    OPEN RESULTSET FOR 
        SELECT HI.ITEMID, HI.ITEMNAME, HI.ITEMCATEGORY, HI.AUCTIONSTARTTIME, HI.AUCTIONENDTIME, HARAMBASE_GETPRICE_FUNC(HI.ITEMID) AS CURRENTBID, GET_STATUS_FUNC(HI.ITEMID) AS STATUS 
        FROM HARAMBASE_ITEM HI 
        WHERE UPPER(HI.ITEMNAME) LIKE '%'||UPPER(KEYWORD)||'%' OR SOUNDEX(KEYWORD) = SOUNDEX(HI.ITEMNAME);
  END IF;
  
END SEARCH_ITEM_PRO;